apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: posts-app
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
        - name: posts-app
          image: abdulrahmanfawzy/posts-app
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: posts-app-service
spec:
  type: NodePort
  selector:
    app: posts-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30000